spring:
  application-name: "streaming-etl"
  kafka:
    bootstrap-servers: "localhost:9092"
    client-id: "streaming-etl"
    streams:
      properties:
        application.server: "localhost:8081"
    properties:
      max.partition.fetch.bytes: 100000000
    consumer:
      group-id: "streaming-etl-group"
    producer:
      group-id: "streaming-etl-group"
server:
  port: 8081

